resource_group_name = "rg-aks-prod"
environment         = "prod"
vnet_name           = "my-vnet"
aks_cluster_name    = "aks-prod"
acr_name            = "acrprodassignmnet2"
key_vault_name      = "kv-prod-123"
log_analytics_name  = "law-prod"
